### ISSUE TITLE
Move GW solution proxy implementation to VMware

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/gp-glasswallsolutions-website#8]
Move GW solution proxy implementation to VMware: https://github.com/k8-proxy/gp-glasswallsolutions-website

@mahnouman will provide access.

**Comment by MariuszFerdyn** [comment]
Deployed on VmWare:
91.109.25.87 glasswallsolutions.com.glasswall-icap.com
91.109.25.87 www.glasswallsolutions.com.glasswall-icap.com

**Comment by MariuszFerdyn** [comment]
91.109.25.87 glasswallsolutions.com.glasswall-icap.com
91.109.25.87 www.glasswallsolutions.com.glasswall-icap.com
91.109.25.87 glasswallsolutions.com
91.109.25.87 www.glasswallsolutions.com

**Comment by GINAGC** [comment]
@MariuszFerdyn at this moment ping to glasswallsolutions.com.glasswall-icap.com is resolved as 54.154.105.24, which is the AWS deployment. Can you shut down the one in AWS? Thanks
